### PR TITLE
Update/Fix Turkish Translation

### PR DESCRIPTION
**Pull request by bitigchi**

### CODE REVIEW

**Comment by humdingerb** [comment]
Thanks!

**Comment by bitigchi** [comment]
No problem!

It feels like some strings are still missing, is it possible to a re-export and check? Maybe uploading them to Polyglot would be nice.

**Comment by humdingerb** [comment]
Hmm... Is PhotoGrabber actually using those translations? I don't see any preference and a quick look doesn't show how those files are used at all.

**Comment by bitigchi** [comment]
It does not even start for me on 64-bit. I am not able to assess whether translations are used or not, on current release menu labels are not translated.

Снимок экрана 2021-11-26 в 17 26 54

**Pull request merged**
